services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: n8n
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: claudia
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 1234
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 10000
